name: build-windows

on:
  push:
    paths:              
      - "**/*.py"
      - "**/*.spec"
      - "back/**"
      - "front/**"

jobs:
  win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pywebview pyinstaller

      - name: Build exe
        run: |
          pyinstaller build.spec
          dir dist\miniSW   # simple listing pour vérifier

      - uses: actions/upload-artifact@v4
        with:
          name: miniSW-win
          path: dist/miniSW/**