# .github/workflows/build-desktop.yml
name: build-desktop

on:
  push:
    paths:
      - "**/*.py"
      - "**/*.spec"
      - "back/**"
      - "front/**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pywebview pyinstaller

      - name: PyInstaller
        run: |
          pyinstaller --clean --noconfirm build.spec

      - name: Show dist contents
        if: runner.os == 'Windows'
        run: dir dist\miniSW
      - name: Show dist contents
        if: runner.os != 'Windows'
        run: ls -R dist/miniSW

      - uses: actions/upload-artifact@v4
        with:
          name: miniSW-${{ runner.os }}
          path: |
            dist/miniSW/**
