# .github/workflows/build-desktop.yml
name: build-desktop

on:
  push:
    paths:
      - "**/*.py"
      - "**/*.spec"
      - "back/**"
      - "front/**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pywebview pyinstaller

      - name: Install Node deps & build Nuxt
        working-directory: front
        run: |
          npm ci             # ou pnpm i / yarn install
          npm run build      # génère .output/public

      - name: Copy static bundle
        shell: bash
        run: |
          rm -rf back/static
          mkdir -p back/static
          cp -r front/.output/public/. back/static/

      - name: PyInstaller
        run: |
          pyinstaller --clean --noconfirm build.spec

      - uses: actions/upload-artifact@v4
        with:
          name: miniSW-${{ runner.os }}
          path: dist/miniSW/**
